<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/transaction.proto

namespace wavesplatform\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>waves.BurnTransactionData</code>
 */
class BurnTransactionData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.waves.Amount asset_amount = 1;</code>
     */
    protected $asset_amount = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \wavesplatform\Protobuf\Amount $asset_amount
     * }
     */
    public function __construct($data = NULL) {
        \wavesplatform\ProtobufMetadata\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.waves.Amount asset_amount = 1;</code>
     * @return \wavesplatform\Protobuf\Amount|null
     */
    public function getAssetAmount()
    {
        return $this->asset_amount;
    }

    public function hasAssetAmount()
    {
        return isset($this->asset_amount);
    }

    public function clearAssetAmount()
    {
        unset($this->asset_amount);
    }

    /**
     * Generated from protobuf field <code>.waves.Amount asset_amount = 1;</code>
     * @param \wavesplatform\Protobuf\Amount $var
     * @return $this
     */
    public function setAssetAmount($var)
    {
        GPBUtil::checkMessage($var, \wavesplatform\Protobuf\Amount::class);
        $this->asset_amount = $var;

        return $this;
    }

}

