<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/transaction.proto

namespace wavesplatform\Protobuf;

if (false) {
    /**
     * This class is deprecated. Use wavesplatform\Protobuf\DataTransactionData\DataEntry instead.
     * @deprecated
     */
    class DataTransactionData_DataEntry {}
}
class_exists(DataTransactionData\DataEntry::class);
@trigger_error('wavesplatform\Protobuf\DataTransactionData_DataEntry is deprecated and will be removed in the next major release. Use wavesplatform\Protobuf\DataTransactionData\DataEntry instead', E_USER_DEPRECATED);

