<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/invoke_script_result.proto

namespace wavesplatform\Protobuf;

if (false) {
    /**
     * This class is deprecated. Use wavesplatform\Protobuf\InvokeScriptResult\Burn instead.
     * @deprecated
     */
    class InvokeScriptResult_Burn {}
}
class_exists(InvokeScriptResult\Burn::class);
@trigger_error('wavesplatform\Protobuf\InvokeScriptResult_Burn is deprecated and will be removed in the next major release. Use wavesplatform\Protobuf\InvokeScriptResult\Burn instead', E_USER_DEPRECATED);

