<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/invoke_script_result.proto

namespace wavesplatform\Protobuf;

if (false) {
    /**
     * This class is deprecated. Use wavesplatform\Protobuf\InvokeScriptResult\SponsorFee instead.
     * @deprecated
     */
    class InvokeScriptResult_SponsorFee {}
}
class_exists(InvokeScriptResult\SponsorFee::class);
@trigger_error('wavesplatform\Protobuf\InvokeScriptResult_SponsorFee is deprecated and will be removed in the next major release. Use wavesplatform\Protobuf\InvokeScriptResult\SponsorFee instead', E_USER_DEPRECATED);

