<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/invoke_script_result.proto

namespace wavesplatform\Protobuf;

if (false) {
    /**
     * This class is deprecated. Use wavesplatform\Protobuf\InvokeScriptResult\Call instead.
     * @deprecated
     */
    class InvokeScriptResult_Call {}
}
class_exists(InvokeScriptResult\Call::class);
@trigger_error('wavesplatform\Protobuf\InvokeScriptResult_Call is deprecated and will be removed in the next major release. Use wavesplatform\Protobuf\InvokeScriptResult\Call instead', E_USER_DEPRECATED);

