<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/invoke_script_result.proto

namespace wavesplatform\Protobuf;

if (false) {
    /**
     * This class is deprecated. Use wavesplatform\Protobuf\InvokeScriptResult\LeaseCancel instead.
     * @deprecated
     */
    class InvokeScriptResult_LeaseCancel {}
}
class_exists(InvokeScriptResult\LeaseCancel::class);
@trigger_error('wavesplatform\Protobuf\InvokeScriptResult_LeaseCancel is deprecated and will be removed in the next major release. Use wavesplatform\Protobuf\InvokeScriptResult\LeaseCancel instead', E_USER_DEPRECATED);

