<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/order.proto

namespace wavesplatform\Protobuf;

if (false) {
    /**
     * This class is deprecated. Use wavesplatform\Protobuf\Order\PriceMode instead.
     * @deprecated
     */
    class Order_PriceMode {}
}
class_exists(Order\PriceMode::class);
@trigger_error('wavesplatform\Protobuf\Order_PriceMode is deprecated and will be removed in the next major release. Use wavesplatform\Protobuf\Order\PriceMode instead', E_USER_DEPRECATED);

