<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/transaction.proto

namespace wavesplatform\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>waves.SponsorFeeTransactionData</code>
 */
class SponsorFeeTransactionData extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.waves.Amount min_fee = 1;</code>
     */
    protected $min_fee = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \wavesplatform\Protobuf\Amount $min_fee
     * }
     */
    public function __construct($data = NULL) {
        \wavesplatform\ProtobufMetadata\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.waves.Amount min_fee = 1;</code>
     * @return \wavesplatform\Protobuf\Amount|null
     */
    public function getMinFee()
    {
        return $this->min_fee;
    }

    public function hasMinFee()
    {
        return isset($this->min_fee);
    }

    public function clearMinFee()
    {
        unset($this->min_fee);
    }

    /**
     * Generated from protobuf field <code>.waves.Amount min_fee = 1;</code>
     * @param \wavesplatform\Protobuf\Amount $var
     * @return $this
     */
    public function setMinFee($var)
    {
        GPBUtil::checkMessage($var, \wavesplatform\Protobuf\Amount::class);
        $this->min_fee = $var;

        return $this;
    }

}

