<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/amount.proto

namespace wavesplatform\ProtobufMetadata;

class Amount
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ë
waves/amount.protowaves"*
Amount
asset_id (
amount (B™
com.wavesplatform.protobufZ9github.com/wavesplatform/gowaves/pkg/grpc/generated/wavesªWavesÊwavesplatform\\Protobufâwavesplatform\\ProtobufMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

