<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/invoke_script_result.proto

namespace wavesplatform\Protobuf\InvokeScriptResult\Call\Argument;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>waves.InvokeScriptResult.Call.Argument.List</code>
 */
class PBList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .waves.InvokeScriptResult.Call.Argument items = 1;</code>
     */
    private $items;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\wavesplatform\Protobuf\InvokeScriptResult\Call\Argument>|\Google\Protobuf\Internal\RepeatedField $items
     * }
     */
    public function __construct($data = NULL) {
        \wavesplatform\ProtobufMetadata\InvokeScriptResult::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .waves.InvokeScriptResult.Call.Argument items = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * Generated from protobuf field <code>repeated .waves.InvokeScriptResult.Call.Argument items = 1;</code>
     * @param array<\wavesplatform\Protobuf\InvokeScriptResult\Call\Argument>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \wavesplatform\Protobuf\InvokeScriptResult\Call\Argument::class);
        $this->items = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(PBList::class, \wavesplatform\Protobuf\InvokeScriptResult_Call_Argument_List::class);

