<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/invoke_script_result.proto

namespace Waves;

if (false) {
    /**
     * This class is deprecated. Use Waves\InvokeScriptResult\Invocation instead.
     * @deprecated
     */
    class InvokeScriptResult_Invocation {}
}
class_exists(InvokeScriptResult\Invocation::class);
@trigger_error('Waves\InvokeScriptResult_Invocation is deprecated and will be removed in the next major release. Use Waves\InvokeScriptResult\Invocation instead', E_USER_DEPRECATED);

