name: PHPUnit

on: [ push, pull_request ]

jobs:
  tests:
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        #os: [ ubuntu-latest, windows-latest, macos-latest ]
        os: [ ubuntu-latest ]
        php-versions: [ '7.4', '8.1' ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: gmp, pdo_sqlite

    - name: PHP version
      run: php -v

    - name: Composer validate
      run: composer validate

    - name: Composer install
      run: composer install

    - name: PHPUnit tests
      env:
        WAVES_CONFIG: ${{ secrets.WAVES_CONFIG }}
      run: php vendor/bin/phpunit tests
